import type { Metadata } from "next"
import "./globals.css"
import { ThemeProvider } from "@mui/material"
import theme from "@/theme/theme"
import ReduxProvider from "@/store/provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
        <body>
        <ReduxProvider>
          
          <ThemeProvider theme={theme}>
              {children}
          </ThemeProvider>
        </ReduxProvider>
        </body>
    </html>
  )
}